clc
close all
scrsz = get(0,'ScreenSize');
figure( 'WindowStyle', 'normal', ...  %%%'normal'
                  'Visible'     ,'on', ...
                  'NumberTitle' ,'off', ...
                  'Name'        ,'Wrong format', ...
                  'Resize'      ,'on', ...
                  'Colormap'    ,[], ...
                  'MenuBar'     ,'none',...
                  'ToolBar' 	,'none', ...
                 'OuterPosition',[scrsz(4)/2 scrsz(4)/5 scrsz(3)/1.9 scrsz(4)/1.61]);
plot(2000,800,'.w')
hold on
plot(1,1,'.w')
text(10,400,['\fontsize{12} Excel data spreadsheet  must be column-oriented and ',...
 '\newline must have at least 3 columns (3D point localizations) with column headers "x", "y", "z".',...
 '\newline (for calibration data all "z" can be zeros)',...
 '\newline \newline If possible, the following additional columns should contain :\newline - position accuracy (in nm) in xy with header "pa",',...
 '\newline - position accuracy (in nm) along the axis z with header "paz",',...
 '\newline - intensity of the point with the header "intensity",',...
 '\newline - and the frame number with the "frame" header.',... 
 '\newline ',...
 '\newline\newline In the absence of these columns they will be automatically generated \newline  with default values typical for this type of nanoscopic samples.',...
])

title ('\fontsize{16} Wrong Data-Format')
whitebg('w')
axis off
btn = uicontrol('Style', 'pushbutton', 'String', 'CLOSE',...
        'Position', [20 20 150 40],...
        'Callback','a_close_info');
clear('ax','btn','scrsz','options')

clc

